# Generated by Django 4.2.26 on 2026-02-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthistory',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
