# Generated by Django 4.2.26 on 2026-02-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accounthistory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounthistory',
            name='operation_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='accounthistory',
            name='type',
            field=models.CharField(choices=[('I', 'Inicio'), ('R', 'Rendimento'), ('A', 'Aporte'), ('W', 'Retirada'), ('E', 'Encerrada'), ('V', 'Reativação')], max_length=1),
        ),
    ]
